name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    # --- THIS IS THE NEW SECTION ---
    # This block tells GitHub Actions to start up other Docker containers
    # that our job can use.
    services:
      # We are defining a service named 'mongodb'.
      mongodb:
        # We tell it to use the official 'mongo' image from Docker Hub.
        image: mongo:latest
        # This maps the container's internal port 27017 to a port on the
        # host machine, making it accessible to our tests.
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Now, when this step runs, a MongoDB instance will be running
      # at localhost:27017, ready to accept connections.
      - name: Run tests
        run: npm test
